# Auto-generated from .repo.toml by 'just repo_toml_generate'
# DO NOT EDIT THIS FILE MANUALLY - regenerate with: just repo_toml_generate

# About section
REPO_DESCRIPTION="Coredns with dnscontrol example 📛🌤"
REPO_LICENSE=""
REPO_TOPICS="coredns,dns-server,dnscontrol,example"

# URLs section
REPO_GIT_SSH="git@github.com:fini-net/fini-coredns-example.git"
REPO_WEB_URL="https://github.com/fini-net/fini-coredns-example"

# Derived values
REPO_ORG_NAME="fini-net"
REPO_REPO_NAME="fini-coredns-example"

# Feature flags (strings: "true" or "false")
FLAG_CLAUDE="false"
FLAG_CLAUDE_REVIEW="false"
FLAG_COPILOT_REVIEW="false"
FLAG_STANDARD_RELEASE="true"

# Topics as array (for iteration)
REPO_TOPICS_ARRAY=(
    "coredns"
    "dns-server"
    "dnscontrol"
    "example"
)
